# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radio.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 170)
        MainWindow.setMinimumSize(QtCore.QSize(200, 170))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/radio_24dp_FFB000_FILL1_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.track_name = QtWidgets.QLabel(self.centralwidget)
        self.track_name.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.track_name.setFont(font)
        self.track_name.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.track_name.setMouseTracking(False)
        self.track_name.setStyleSheet("color: rgb(255, 176, 0);")
        self.track_name.setMidLineWidth(-1)
        self.track_name.setAlignment(QtCore.Qt.AlignCenter)
        self.track_name.setWordWrap(True)
        self.track_name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.track_name.setObjectName("track_name")
        self.gridLayout.addWidget(self.track_name, 1, 0, 1, 5)
        self.play_pause = QtWidgets.QPushButton(self.centralwidget)
        self.play_pause.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.play_pause.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.play_pause.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.play_pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/play_arrow_24dp_FFB000_FILL1_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause.setIcon(icon1)
        self.play_pause.setIconSize(QtCore.QSize(48, 48))
        self.play_pause.setAutoDefault(False)
        self.play_pause.setDefault(False)
        self.play_pause.setFlat(True)
        self.play_pause.setObjectName("play_pause")
        self.gridLayout.addWidget(self.play_pause, 3, 2, 1, 1)
        self.name_station = QtWidgets.QLabel(self.centralwidget)
        self.name_station.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name_station.setFont(font)
        self.name_station.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.name_station.setStyleSheet("color: rgb(255, 176, 0);")
        self.name_station.setScaledContents(True)
        self.name_station.setAlignment(QtCore.Qt.AlignCenter)
        self.name_station.setWordWrap(True)
        self.name_station.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.name_station.setObjectName("name_station")
        self.gridLayout.addWidget(self.name_station, 0, 0, 1, 5)
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/skip_previous_24dp_FFB000_FILL1_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon2)
        self.back.setIconSize(QtCore.QSize(32, 32))
        self.back.setFlat(True)
        self.back.setObjectName("back")
        self.gridLayout.addWidget(self.back, 3, 1, 1, 1)
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/skip_next_24dp_FFB000_FILL1_wght400_GRAD0_opsz24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon3)
        self.next.setIconSize(QtCore.QSize(32, 32))
        self.next.setFlat(True)
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Radio"))
        self.track_name.setText(_translate("MainWindow", "Track name"))
        self.name_station.setText(_translate("MainWindow", "Name of station"))
